package com.example.webapptask.controller;

public enum CommandName {
    REGISTRATION_NEW_USER,
    UPDATE_PERSONAL_PAGE,
    AUTHORIZATION_USER,
    UPDATE_NEWS_PAGE,
    UNKNOWN_COMMAND,
    CHANGE_LOCALE,
    PERSONAL_PAGE,
    AUTHORIZATION,
    REGISTRATION,
    UPDATE_USER,
    UPDATE_NEWS,
    DELETE_NEWS,
    MAIN_PAGE,
    NEWS_PAGE,
    OUT_USER,
    ADD_NEWS,
    NEWS
}