package com.example.webapptask.controller;

public enum CommandName {
    GO_TO_UPDATE_PERSONAL_PAGE,
    GO_TO_FAVOURITE_NEWS_PAGE,
    GO_TO_AUTHORIZATION_PAGE,
    GO_TO_REGISTRATION_PAGE,
    GO_TO_UPDATE_NEWS_PAGE,
    DELETE_FROM_FAVOURITE,
    REGISTRATION_NEW_USER,
    GO_TO_READ_NEWS_PAGE,
    GO_TO_PERSONAL_PAGE,
    GO_TO_ADD_NEWS_PAGE,
    AUTHORIZATION_USER,
    ADD_TO_FAVOURITE,
    UNKNOWN_COMMAND,
    CHANGE_LOCALE,
    UPDATE_USER,
    UPDATE_NEWS,
    DELETE_NEWS,
    MAIN_PAGE,
    OUT_USER,
    ADD_NEWS
}